### ISSUE TITLE
Having trouble restoring a mysql backup

### ISSUE THREAD

**Issue by bkuhl** [davidsoergel/s3napback#7]
I'm running a quick test on restoring in my production environment and I'm running into a snag.  

```
# java -jar /usr/local/s3napback/js3tream.jar --debug -n -f -v -K /usr/local/s3napback/key.txt -o -b "my-bucket:/MySQL/--all-databases-10:00000000000000000000" | tar xvz
Sending S3 data to STDOUT
Bucket [biblebowl-backup]
Prefix [/MySQL/--all-databases-10:00000000000000000000]
0.00K transfered

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I'm showing in Amazon S3 that this file is almost 700k in size:
![screen shot 2015-06-28 at 11 09 53 pm](https://cloud.githubusercontent.com/assets/524933/8400336/d1ea3a6a-1dea-11e5-9908-81b63d4492c7.png)

The breadcrumb is **All Buckets / my-repo / MySQL" so I believe my path is correct.  Do you see anything else I might have missed?

**Comment by davidsoergel** [comment]
I believe the retrieval from S3 is working fine, but unlike filesystem backups, MySQL backups are just gzipped but not tarred-- so the issue is that you're piping into "tar xvf".

For simplicity, try writing the output to a file (i.e., replace "| tar xvf" with "> mysql-backup.gz" or some such.  Then gunzip that file, and observe that the result is a valid mysql dump.

Assuming that's all good, you could in the future pipe directly to gunzip, and even pipe the decompressed stream directly to mysql if you need full automation.
